RadiomicsEnabler/urls.py
# Radiomics Enabler(R) - Unleash the potential of your medical images archives (PACS) for research
#
#     Copyright (C) 2017-2019 Medexprim
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see https://www.gnu.org/licenses/.
#
#     Contact : contact@medexprim.com

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from . import views

urlpatterns = [
    url(r'^favicon.ico$', RedirectView.as_view(url='/static/RadiomicsEnabler/favicon/favicon.ico')),
    url(r'^$', auth_views.LoginView.as_view(template_name='RadiomicsEnabler/login.html'), name='home'),
    url(r'^login/$', auth_views.LoginView.as_view( template_name='RadiomicsEnabler/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view( template_name='RadiomicsEnabler/logout.html'), name='logout'),
    url(r'^Projects$', views.ProjectListView.as_view(), name='projectList'),
    url(r'^Project/(?P<pk>[0-9]+)/$', views.ProjectDetailView,name='projectDetails'),
    url(r'^Project/add/$', views.ProjectCreate.as_view(), name='projectCreate'),
    url(r'^Project/(?P<pk>[0-9]+)/archive/$', views.ProjectArchive.as_view(), name='projectArchive'),
    url(r'^Project/(?P<pk>[0-9]+)/modify/$', views.ProjectModify.as_view(), name='projectModify'),
    url(r'^Project/(?P<pk>[0-9]+)/add/$', views.BatchCreate.as_view(), name='batchCreate'),
    url(r'^Batch/(?P<pk>[0-9]+)/archive/$', views.BatchArchive.as_view(), name='batchArchive'),
    url(r'^Batch/(?P<pk>[0-9]+)/validate/$', views.BatchValidate.as_view(), name='batchValidate'),
    url(r'^Batch/(?P<pk>[0-9]+)/modify/$', views.BatchModify.as_view(), name='batchModify'),
    url(r'^Batch/(?P<pk>[0-9]+)/$', views.BatchDetail.as_view(), name='batchDetail'),
    url(r'^Batch/(?P<pk>[0-9]+)/query/add/$', views.BatchQueryCreate.as_view(), name='batchQueryCreate'),
    url(r'^Batch/(?P<bpk>[0-9]+)/Query/(?P<pk>[0-9]+)/detail/$', views.QueryResults.as_view(), name='queryResults'),
    url(r'^Batch/(?P<bpk>[0-9]+)/Query/(?P<pk>[0-9]+)/series/$', views.SeriesResults.as_view(), name='seriesDetail'),
    url(r'^Batch/(?P<pk>[0-9]+)/Extraction/(?P<uuid>[a-z0-9-]+)/$', views.ExtractionProgress.as_view(), name='extractionProgress'),
    url(r'^Study/(?P<pk>[0-9]+)/archive/$', views.StudyArchive.as_view(), name='studyArchive'),
    url(r'^Series/(?P<pk>[0-9]+)/archive/$', views.SeriesArchive.as_view(), name='seriesArchive'),
    url(r'^ListQuery/$', views.ListQuery, name='listQuery'),
    url(r'^ListQuery/(?P<pk>[0-9]+)/modify/$', views.SearchListQueryModify.as_view(), name='listQueryModify' ),
    url(r'^Search/(?P<pk>[0-9]+)/Extraction/$', views.SearchProgress.as_view(),name='searchProgress'),
    url(r'^Search/(?P<pk>[0-9]+)/Series/$', views.SeriesSearchProgress.as_view(),name='seriesSearchProgress'),
]

sitebase/urls.py
# Radiomics Enabler(R) - Unleash the potential of your medical images archives (PACS) for research
#
#     Copyright (C) 2017-2019 Medexprim
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see https://www.gnu.org/licenses/.
#
#     Contact : contact@medexprim.com

"""Radiomics Enabler URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^RadiomicsEnabler/', include('RadiomicsEnabler.urls')),
    url(r'^admin/', admin.site.urls),
]

RadiomicsEnabler/models.py
# Radiomics Enabler(R) - Unleash the potential of your medical images archives (PACS) for research
#
#     Copyright (C) 2017-2019 Medexprim
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see https://www.gnu.org/licenses/.
#
#     Contact : contact@medexprim.com

from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Destination( models.Model):
    name = models.CharField( max_length=50, verbose_name='DICOM Destination',unique=True)
    short_name = models.CharField( max_length=50 )
    port = models.IntegerField()
    aetitle = models.CharField(max_length=16, verbose_name="AE Title")
    ipaddress = models.GenericIPAddressField()
    def __str__(self):
        return self.name

class Project(models.Model):
    name = models.CharField(max_length=50, verbose_name='Project Name',unique=True)
    creation_date = models.DateField(auto_now_add=True, verbose_name='Creation Date')
    modification_date = models.DateField(null = True, blank=True, verbose_name='Last Update')
    description = models.TextField(max_length=250, verbose_name='Description', blank=True )
    approval_info = models.TextField(max_length=250, verbose_name='Approval Information', blank=True )
    owner = models.CharField(max_length=50, verbose_name='Owner', blank=True, null=True )
    destination = models.ForeignKey( Destination, blank = True, null= True, on_delete=models.SET_NULL )
    archived = models.BooleanField( default=False, verbose_name = 'Archived' )
    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    project = models.ManyToManyField( Project, blank = True, verbose_name= 'Project'  )
    agreement = models.BooleanField( default=False, verbose_name='Signed Warning')
    def __str__(self):
        return self.user.get_username()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Batch(models.Model):
    S = 'S'
    D = 'D'
    P = 'P'
    E = 'E'
    W = 'W'
    V = 'V'
    C = 'C'
    I = 'I'
    status_choices=((I, 'Interrupted'),(V,'Validated'),(E,'Error'),(D,'Done'), (W,'Waiting to be extracted'), (S,'Scheduled'), (P,'Processing'), (C,'Completed') )
    name = models.CharField(max_length=25 )
    description = models.TextField(max_length=250, verbose_name='Description', blank=True )
    project = models.ForeignKey( Project, on_delete=models.CASCADE )
    status = models.CharField( max_length=1, choices = status_choices, default=W )
    destination = models.CharField(blank=True, max_length=150)
    extraction_datetime = models.DateTimeField( null = True, blank=True, verbose_name = 'Extracted on' )
    validation_datetime = models.DateTimeField( null = True, blank=True, verbose_name = 'Validated on' )
    scheduled_datetime = models.DateTimeField( null = True, blank=True, verbose_name = 'Scheduled Date' )
    preparation_datetime = models.DateTimeField( null = True, blank=True, verbose_name = 'Prepared on' )
    number_of_patients = models.IntegerField( default= 0, verbose_name = 'Number of Patients' )
    number_of_studies = models.IntegerField( default= 0, verbose_name = 'Number of Studies' )
    number_of_series = models.IntegerField( default= 0, verbose_name = 'Number of Series' )
    number_of_images = models.IntegerField( default= 0, verbose_name = 'Number of Images' )
    size_in_bytes = models.BigIntegerField( default= 0, verbose_name = 'File Size' )
    archived = models.BooleanField( default=False, verbose_name = 'Archived' )
    num_extractions = models.IntegerField( default= 0, verbose_name = 'Number of Extractions' )
    num_extractions_success =  models.IntegerField( default= 0, verbose_name = 'Number of Successful Extractions' )
    num_extractions_failure =  models.IntegerField( default= 0, verbose_name = 'Number of Extractions in Error' )
    extractions_running = models.BooleanField( default = False )
    taskIds = models.TextField( default='', blank=True, verbose_name='Task IDs')

    class Meta:
        unique_together = ('name','project')

    def __str__(self):
        return self.name + ' (' + self.project.name + ')'

class Search(models.Model):
    study_date_from = models.DateField( verbose_name="From", blank = True, null = True )
    study_date_to = models.DateField( verbose_name="To", blank = True, null = True )
    patient_last_name = models.CharField(max_length=50, blank = True, verbose_name="Patient's last name" )
    patient_first_name = models.CharField(max_length=50, blank = True, verbose_name="Patient's first name" )
    patient_birth_date = models.DateField( verbose_name="Birth date", blank = True, null = True )
    patient_id = models.CharField(max_length=64, verbose_name="Patient ID", blank=True)
    patient_list = models.FileField(verbose_name="Patient list", blank = True, null = True, upload_to='uploads/patient_lists/%Y/%m/%d/' )
    CR = 'CR'
    CT = 'CT'
    MR = 'MR'
    NM = 'NM'
    US = 'US'
    PT = 'PT'
    XA = 'XA'
    MG = 'MG'
    PX = 'PX'
    modality_choices = ( (CR,'CR: Computed Radiography'),
                         (CT,'CT: Computed Tomography'),
                         (MR,'MR: Magnetic Resonance'),
                         (NM,'NM: Nuclear Medicine'),
                         (US,'US: Ultrasound'),
                         (PT,'PT: Positron emission tomography (PET)'),
                         (XA, 'XA: X-Ray Angiography'),
                         (MG, 'MG: Mammography'),
                         (PX,'PX: Panoramic X-Ray') )
    modality = models.CharField(max_length=60, verbose_name="Modality type(s)", blank=True )
    exam_types = models.CharField(max_length=180, verbose_name = "Exam type(s)", blank = True)
    batch = models.ForeignKey( Batch, on_delete=models.CASCADE )
    archived = models.BooleanField( default=False, verbose_name = 'Archived' )
    notRun = models.BooleanField( default=True, verbose_name = 'Not run' )
    rtrnStatus = models.TextField(blank=True, verbose_name='Search Status')
    numberOfResults = models.IntegerField(default=0,verbose_name="Number of results")
    isFinished = models.BooleanField( default=False, verbose_name="Is finished")
    advanced_search = models.FileField(verbose_name="Advanced search", blank = True, null = True, upload_to='uploads/advanced_search/%Y/%m/%d/' )
    taskId = models.TextField( default='', blank=True, verbose_name='Search Task ID')
    nSeriesSearch = models.IntegerField(default=0)
    seriesTaskIds = models.TextField( default='', blank=True, verbose_name='Series Task IDs')

    def __str__(self):
        search_str = 'Search (Batch={:s})->'.format( str(self.batch) )
        if self.study_date_from:
            search_str = search_str + 'From:' + str( self.study_date_from)
        if self.study_date_to:
            search_str = search_str + ' To:' + str(self.study_date_to)
        if self.modality:
            search_str = search_str + ' Modality:' + self.modality
        if self.patient_last_name:
            search_str = search_str + ' Last name:' + self.patient_last_name
        if self.patient_first_name:
            search_str = search_str + ' First name:' + self.patient_first_name
        if self.patient_birth_date:
            search_str = search_str + ' Birth date:' + str( self.patient_birth_date )
        if self.patient_id:
            search_str = search_str + ' Patient ID:' + self.patient_id
        if self.patient_list:
            search_str = search_str + ' Patient List:' + str( self.patient_list )
        return search_str


class Study(models.Model):
    CO = 'C'
    PE = 'P'
    ER = 'E'
    SE = 'S'
    status_choices = ( (CO,'Complete'),
                        (PE,'Pending'),
                        (ER,'Error'),
                       (SE, 'Series'), )
    patient_id = models.CharField(max_length=64, verbose_name="Patient ID", blank=True)
    dicom_uid = models.CharField(max_length=64, verbose_name="DICOM ID", blank=True)
    study_id = models.CharField(max_length=64, verbose_name="Study ID", blank=True)
    patient_last_name = models.CharField(max_length=50, blank = True, verbose_name="Patient's last name" )
    patient_first_name = models.CharField(max_length=50, blank = True, verbose_name="Patient's first name" )
    patient_birth_date = models.DateField( verbose_name="Birth date", blank = True, null = True )
    study_date = models.DateField(verbose_name="Study date", blank = True, null = True )
    event_date = models.DateField(verbose_name="Event date", blank = True, null = True )
    modality = models.CharField(max_length=50, blank = True )
    study_description = models.CharField(max_length=64, blank = True, verbose_name='Study Description')
    search = models.ForeignKey( Search, on_delete=models.CASCADE, null=True )
    num_search = models.IntegerField(default=0)
    selected = models.BooleanField( default=False, verbose_name= "Selected")
    archived = models.BooleanField( default=False, verbose_name = 'Archived' )

RadiomicsEnabler/templates/RadiomicsEnabler/base.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <link rel="stylesheet" href="{% static 'RadiomicsEnabler/style.css' %}"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'RadiomicsEnabler/favicon/favicon.ico' %}"/>
    <title>{% block title %}Radiomics Enabler{% endblock %}</title>
    <style>
        #leftheader { float: left;
                        width: 50%;
                        align: left;
                        vertical-align: middle;
                        }
        #rightheader { float: right;
                        width: 50%;
                        text-align:right;
                        vertical-align: middle;
                      }
        #navheader { clear: both; }
        td.reTitle {
            color: rgb(0,94,156);
            font-size: 3em;
            }
        .errorlist { color:rgb(240,10,10); }

    </style>
    <script type="text/javascript">

        // this function is used to clear the setTimeout() queue so that button clicks will not be lost if the page reloads
        function clearTimeouts() { // clear all timeouts

            var id = window.setTimeout(function() {}, 0);

            while (id--) {
                window.clearTimeout(id); // will do nothing if no timeout with id is present
            }
            return true; //see https://stackoverflow.com/questions/7347786/html-anchor-tag-with-javascript-onclick-event

        }

    </script>
    {% block headinfo %}{% endblock %}
</head>
<body>
    <div id="header">
        <div id="leftheader">
            <table cellpadding="5" valign="middle">
                <tr><td><img src="{% static 'RadiomicsEnabler/images/ILLUSTRATION-WEB.png' %}"/></td><td class="reTitle">Radiomics Enabler</td></tr>
            </table>
        </div>
        <div id="rightheader">
            <table cellpadding="5" valign="middle" align="right">
                <tr><td>{{ user.first_name }} {{ user.last_name}}</td></tr>
                <tr><td align="center"><button class="myButton" onclick="location.href='{% url 'logout' %}'" name="Logout">Logout</button></td></tr>
            </table>

        </div>

        <div id="navheader">{% block navheader %}<a href="{% url 'projectList' %}">Home</a>{% endblock %}</div>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>

</body>
</html>

RadiomicsEnabler/templates/RadiomicsEnabler/batch_confirm_delete.html
{% extends "RadiomicsEnabler/base.html" %}
{% load static %}

{% block title %}{{ block.super }}: Delete Batch {% endblock %}

{% block navheader %}{{ block.super }}><a href="{% url 'projectDetails' object.project.pk %}">{{ object.project.name }}</a>>Delete batch{% endblock %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" name="confirm" value="Confirm" />
        <input type="submit" name="cancel" value="Cancel" />
    </form>

{% endblock content %}

RadiomicsEnabler/templates/RadiomicsEnabler/batch_confirm_validate.html
{% extends "RadiomicsEnabler/base.html" %}
{% load static %}

{% block title %}{{ block.super }}: Validate Batch {% endblock %}

{% block navheader %}{{ block.super }}><a href="{% url 'projectDetails' object.project.pk %}">{{ object.project.name }}</a>>Validate batch{% endblock %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to validate Batch "{{ object }}" from Project "{{ object.project.name }}"? Your batch will be moved to the list of archived batches and all images will be deleted from the Radiomics Enabler® server.</p>
        <input type="submit" name="confirm" value="Confirm" />
        <input type="submit" name="cancel" value="Cancel" />
    </form>

{% endblock content %}

RadiomicsEnabler/templates/RadiomicsEnabler/batch_modify.html
{% extends "RadiomicsEnabler/base.html" %}
{% load static %}

{% block title %}{{ block.super }}: Modify Batch {% endblock %}

{% block navheader %}{{ block.super }}><a href="{% url 'projectDetails' object.project.pk %}">{{ object.project.name }}</a>>Modify batch{% endblock %}

{% block headinfo %}

    <style>

    div.labels {
        padding-right: 1em;
        }

    #container {
        display: table;
        padding-top: 2em;
        padding-bottom: 1em;
    }
    #container > div {
        display: table-row;

    }
    #container > div > div {
        display: table-cell;
        padding-bottom:1em;
    }
    </style>

{% endblock %}


{% block content %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <center>
        <div id="container">
            <div>
                <div class="labels"></div>
                <div>{{ form.name.errors }}</div>
            </div>
            <div>
                <div class="labels">{{ form.name.label_tag }}</div>
                <div>{{ form.name }}</div>
            </div>
            <div>
                <div class="labels">{{ form.description.label_tag }}</div>
                <div>{{ form.description }}</div>
            </div>
        </div>
        </center>
        <center>
            <input border=0 type="submit" value="Validate" class="myButton" name="_validate"/> <span class="espace"/>
            <button onClick="location.href='{% url 'projectDetails' object.project.pk %}'" class="myButton" name="_cancel">Cancel</button>
        </center>
    </form>






{% endblock content %}

RadiomicsEnabler/templates/RadiomicsEnabler/confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
	    <link rel="stylesheet" href="{% static 'RadiomicsEnabler/styles.css' %}" />
    </head>
    <body>
        <div class="pageheader">
            <table>
                <tr>
                    <td><img src="{% static 'RadiomicsEnabler/images/ILLUSTRATION-WEB.png' %}"/> </td>
                    <td> RADIOMICS ENABLER </td>
                    <td> User Name Logout</td>
                </tr>
            </table>
        </div>

    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" name="confirm" value="Confirm" />
        <input type="submit" name="cancel" value="Cancel" />
    </form>

    </body>
</html>

RadiomicsEnabler/templates/RadiomicsEnabler/extractionProgress.html
{% extends "RadiomicsEnabler/base.html" %}
{% load static %}

{% block title %}{{ block.super }}: Batch Extraction{% endblock %}

{% block headinfo %}
    <style>
        .loader {
          border: 16px solid #f3f3f3;
          border-radius: 50%;
          border-top: 16px solid blue;
          border-bottom: 16px solid blue;
          width: 120px;
          height: 120px;
          -webkit-animation: spin 2s linear infinite;
          animation: spin 2s linear infinite;
        }

        @-webkit-keyframes spin {
          0% { -webkit-transform: rotate(0deg); }
          100% { -webkit-transform: rotate(360deg); }
        }

        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
    </style>

    <script type="text/javascript"
            src="{% static 'RadiomicsEnabler/scripts/jQuery-2.2.4/jquery-2.2.4.min.js' %}"></script>


    <script type="text/javascript">


        $(document).ready ( function(){
            var a = '{{ runStatus }}';
            if ( a == 0 ){
                $("#spinner").css("display",'none');
                $("#StopRetrieval").hide();
                $("#processing").css("display",'none');
            }
            else {
                $("#finished").css("display",'none');
            }
            setTimeout(function() { window.location.reload(true) },2000);
         });



    </script>
{% endblock headinfo %}


{% block navheader %}{{ block.super }}><a href="{% url 'projectDetails' batch.project.pk %}" onclick="clearTimeouts()">{{ batch.project.name }}</a>><a href="{% url 'batchDetail' batch.pk %}" onclick="clearTimeouts()">{{ batch.name }}</a>>Extraction{% endblock %}

{% block content %}

<center>
    <div id="spinner" class="loader"></div>
    <div id="message">{{ progressMessage }}</div>
    <div id="buttons">
        <form method="post">
            {% csrf_token %}
            <input type="submit" class="myButton" id="StopRetrieval" name="StopRetrieval" value="Stop retrieval" onclick="clearTimeouts()"/>
        </form>
    </div>
    <div id="processing">
        Your batch is processing.<br/>
        You may go back to your <a href="{% url 'projectDetails' batch.project.pk %}" onclick="clearTimeouts()">project</a> or the <a href="{% url 'projectList' %}" onclick="clearTimeouts()">list of projects</a>.
        You may also logout. Your batch will continue processing.
    </div>
    <div id="finished">
        You may go back to your <a href="{% url 'projectDetails' batch.project.pk %}" onclick="clearTimeouts()">project</a> or the <a href="{% url 'projectList' %}" onclick="clearTimeouts()">list of projects</a>.
        You may also logout.
    </div>

</center>

{% endblock content %}

RadiomicsEnabler/templates/RadiomicsEnabler/search_list_query_modify.html
{% extends "RadiomicsEnabler/base.html" %}
{% load static %}

{% block title %}{{ block.super }}: PACS List Query{% endblock %}

{% block headinfo %}

    <style>
        #content {
            font: normal 12px/15px 'Lucida Grande', Verdana, Helvetica, Arial, sans-serif;
        }
        legend { font-weight: bold; }
        .ui-widget {
            font: normal 12px/15px 'Lucida Grande', Verdana, Helvetica, Arial, sans-serif !important;
        }
    </style>


   <link rel="stylesheet" type="text/css" href="{% static '/RadiomicsEnabler/scripts/jquery-ui-1.12.1.custom/jquery-ui.min.css' %}" />
    <script type="text/javascript"  src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script type="text/javascript"  src="{% static '/RadiomicsEnabler/scripts/jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>
    <script>
    $( function() {
    $( "#id_patient_birth_date" ).datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: "yy-mm-dd",
        minDate: "-120y",
        maxDate: "+0d",
        yearRange: "-120:+0"
        });
     $( "#id_study_date_from" ).datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: "yy-mm-dd",
        minDate: "-120y",
        maxDate: "+0d",
        yearRange: "-120:+0"
        });
      $( "#id_study_date_to" ).datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: "yy-mm-dd",
        minDate: "-120y",
        maxDate: "+0d",
        yearRange: "-120:+0"
        });
     } );
  </script>

{% endblock %}

{% block navheader %}{{ block.super }}><a href="{% url 'projectDetails' search.batch.project.pk %}">{{ search.batch.project.name }}</a>><a href="{% url 'batchDetail' search.batch.pk %}">{{ search.batch.name }}</a>>PACS List Query{% endblock %}

{% block content %}
    <br/>
    <br/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <center>
         {{ form.non_field_errors }}

        <table>
            <tr>
            <td>
                <fieldset>
                    <legend>Study date</legend>
                    {{ form.study_date_from.errors }}
                    {{ form.study_date_to.errors }}
                    <table>
                        <tr><td>{{ form.study_date_from.label_tag }}</td><td>{{ form.study_date_from }}</td></tr>
                        <tr><td>{{ form.study_date_to.label_tag }}</td><td>{{ form.study_date_to }}</td></tr>
                    </table>
                </fieldset>
            </td>
                <td width="5%"></td>
            <td>
                <fieldset>
                    <legend>{{ form.modality.label_tag }}</legend>
                    {{ form.modality.error }}
                    {{ form.modality }}
                </fieldset>
            </td>
            <td width="5%"></td>
            <td width="30%">
                <fieldset>
                    <legend>{{ form.exam_types.label_tag }}</legend>
                    Input a comma separated list of items to be found in the study description.
                    {{ form.exam_types.error }}
                    {{ form.exam_types }}
                </fieldset>
            </td>
            </tr>

        </table>

            <br/>
            <br/>

        <table width="30%">
            <tr>
                <td>
                    <center>
                    <fieldset>
                        <legend>Advanced search</legend>
                                            Indicate an XML file containing your custom advanced search.<br/><br/>
                        {{ form.advanced_search.error }}
                    {{ form.advanced_search }} <button type="button" disabled>Browse...</button>No file selected.<br/><br/>
                   Contact <a href="mailto:contact@medexprim.com">Medexprim</a> to build a custom search.
                    </fieldset>
                    </center>
                </td>
            </tr>
        </table>
        </center>
        <br/>
        <br/>
        <center>
            <input type="submit"  name="validate" value="Validate" class="myButton"/>
            <input type="submit"  name="cancel" value="Cancel" class="myButton" />
        </center>

    </form>

{% endblock content %}